### ISSUE TITLE
Marketplace integration test is flaky

### ISSUE THREAD

**Issue by sveitser** [EspressoSystems/espresso-sequencer#2234]
Seems to have failed here unexpectedly: 

https://github.com/EspressoSystems/espresso-sequencer/actions/runs/11576703691/job/32226342496?pr=2231

**Comment by sveitser** [comment]
```
 ------------
 Nextest run ID c0586692-b066-4f5c-b88b-c03deae16a28 with nextest profile: integration
    Starting 2 tests across 1 binary (38 binaries skipped via profile.integration.default-filter)
       START             tests::integration smoke::test_smoke

running 1 test
test smoke::test_smoke has been running for over 60 seconds
Waiting on Builder Address
Waiting on readiness
Initial State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

thread 'smoke::test_smoke' panicked at tests/smoke.rs:45:17:
New State:
Chain state not incrementing
        block_height: 27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
  TRY 1 FAIL [  90.363s] tests::integration smoke::test_smoke
        light_client_updated: 68

test smoke::test_smoke ... FAILED

failures:

failures:
    smoke::test_smoke

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 90.35s

   RETRY 2/3 [         ] tests::integration smoke::test_smoke

running 1 test
Waiting on Builder Address
Waiting on readiness
Initial State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 68

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

thread 'smoke::test_smoke' panicked at tests/smoke.rs:49:17:
New State:
Transactions not incrementing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

test smoke::test_smoke ... FAILED

failures:

failures:
    smoke::test_smoke

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 6.67s

  TRY 2 FAIL [   6.684s] tests::integration smoke::test_smoke
   RETRY 3/3 [         ] tests::integration smoke::test_smoke

running 1 test
Waiting on Builder Address
Waiting on readiness
Initial State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

thread 'smoke::test_smoke' panicked at tests/smoke.rs:45:17:
New State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

Chain state not incrementing
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test smoke::test_smoke ... FAILED

failures:

failures:
    smoke::test_smoke

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 1 filtered out; finished in 6.46s

  TRY 3 FAIL [   6.470s] tests::integration smoke::test_smoke
   Canceling due to test failure
       START             tests::integration upgrades::test_upgrade

running 1 test
Waiting on Builder Address
Waiting on readiness
Initial State:
        block_height: 27
        transactions: 0
        builder_balance: 1000000000000000000
        recipient_balance: 0
        light_client_updated: 94

test upgrades::test_upgrade has been running for over 60 seconds
Upgrade succeeded @ height 116!
test upgrades::test_upgrade ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 80.42s

        PASS [  80.428s] tests::integration upgrades::test_upgrade
------------
     Summary [ 183.947s] 2 tests run: 1 passed, 1 failed, 0 skipped
  TRY 3 FAIL [   6.470s] tests::integration smoke::test_smoke
error: test run failed
Error: Process completed with exit code 100.
```
